<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Men's Perfumes
            [
                'name' => 'Dahn Al Oudh Moattaq',
                'name_ar' => 'دهن العود معتق',
                'description' => 'Rich and intense Oud fragrance',
                'barcode' => 'PRF001',
                'sku' => 'AJM-DAO-001',
                'category_id' => 1, // Men
                'brand_id' => 1, // Ajmal
                'cost_price' => 150.00,
                'selling_price' => 250.00,
                'stock_quantity' => 50,
                'min_stock_level' => 10,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Hawas',
                'name_ar' => 'هواس',
                'description' => 'Fresh aquatic fragrance for men',
                'barcode' => 'PRF002',
                'sku' => 'RAS-HAW-002',
                'category_id' => 1,
                'brand_id' => 2, // Rasasi
                'cost_price' => 80.00,
                'selling_price' => 150.00,
                'stock_quantity' => 75,
                'min_stock_level' => 15,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Junoon Noir',
                'name_ar' => 'جنون نوار',
                'description' => 'Mysterious and seductive scent',
                'barcode' => 'PRF003',
                'sku' => 'RAS-JNN-003',
                'category_id' => 1,
                'brand_id' => 2,
                'cost_price' => 70.00,
                'selling_price' => 130.00,
                'stock_quantity' => 60,
                'min_stock_level' => 12,
                'size' => '75ml',
                'is_active' => true,
            ],
            [
                'name' => 'Shaghaf Oud',
                'name_ar' => 'شغف عود',
                'description' => 'Passionate Oud blend',
                'barcode' => 'PRF004',
                'sku' => 'SWA-SHG-004',
                'category_id' => 1,
                'brand_id' => 4, // Swiss Arabian
                'cost_price' => 90.00,
                'selling_price' => 170.00,
                'stock_quantity' => 45,
                'min_stock_level' => 10,
                'size' => '75ml',
                'is_active' => true,
            ],
            
            // Women's Perfumes
            [
                'name' => 'Wisal Dhahab',
                'name_ar' => 'وصال ذهب',
                'description' => 'Golden floral fragrance for women',
                'barcode' => 'PRF005',
                'sku' => 'AJM-WSD-005',
                'category_id' => 2, // Women
                'brand_id' => 1,
                'cost_price' => 100.00,
                'selling_price' => 180.00,
                'stock_quantity' => 55,
                'min_stock_level' => 12,
                'size' => '50ml',
                'is_active' => true,
            ],
            [
                'name' => 'Amber Oud Rouge',
                'name_ar' => 'عنبر عود روج',
                'description' => 'Luxurious amber and oud blend',
                'barcode' => 'PRF006',
                'sku' => 'ALH-AOR-006',
                'category_id' => 2,
                'brand_id' => 3, // Al Haramain
                'cost_price' => 120.00,
                'selling_price' => 220.00,
                'stock_quantity' => 40,
                'min_stock_level' => 10,
                'size' => '60ml',
                'is_active' => true,
            ],
            [
                'name' => 'Opulent Musk',
                'name_ar' => 'مسك فاخر',
                'description' => 'Elegant musky fragrance',
                'barcode' => 'PRF007',
                'sku' => 'LAT-OPM-007',
                'category_id' => 2,
                'brand_id' => 5, // Lattafa
                'cost_price' => 60.00,
                'selling_price' => 110.00,
                'stock_quantity' => 80,
                'min_stock_level' => 15,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Raghba',
                'name_ar' => 'رغبة',
                'description' => 'Sweet vanilla and woody notes',
                'barcode' => 'PRF008',
                'sku' => 'LAT-RAG-008',
                'category_id' => 2,
                'brand_id' => 5,
                'cost_price' => 55.00,
                'selling_price' => 100.00,
                'stock_quantity' => 90,
                'min_stock_level' => 20,
                'size' => '100ml',
                'is_active' => true,
            ],
            
            // Unisex Perfumes
            [
                'name' => 'Musk Al Ghazal',
                'name_ar' => 'مسك الغزال',
                'description' => 'Classic white musk',
                'barcode' => 'PRF009',
                'sku' => 'NAB-MAG-009',
                'category_id' => 3, // Unisex
                'brand_id' => 6, // Nabeel
                'cost_price' => 45.00,
                'selling_price' => 85.00,
                'stock_quantity' => 100,
                'min_stock_level' => 25,
                'size' => '50ml',
                'is_active' => true,
            ],
            [
                'name' => 'Layali',
                'name_ar' => 'ليالي',
                'description' => 'Romantic night fragrance',
                'barcode' => 'PRF010',
                'sku' => 'SWA-LAY-010',
                'category_id' => 3,
                'brand_id' => 4,
                'cost_price' => 70.00,
                'selling_price' => 130.00,
                'stock_quantity' => 65,
                'min_stock_level' => 15,
                'size' => '75ml',
                'is_active' => true,
            ],
            
            // Oud Products
            [
                'name' => 'Royal Dehn Al Oud',
                'name_ar' => 'دهن العود الملكي',
                'description' => 'Premium aged Oud oil',
                'barcode' => 'PRF011',
                'sku' => 'ASQ-RDO-011',
                'category_id' => 4, // Oud
                'brand_id' => 7, // Abdul Samad Al Qurashi
                'cost_price' => 200.00,
                'selling_price' => 350.00,
                'stock_quantity' => 30,
                'min_stock_level' => 5,
                'size' => '12ml',
                'is_active' => true,
            ],
            [
                'name' => 'Cambodian Oud',
                'name_ar' => 'عود كمبودي',
                'description' => 'Pure Cambodian Oud chips',
                'barcode' => 'PRF012',
                'sku' => 'ASQ-CAO-012',
                'category_id' => 4,
                'brand_id' => 7,
                'cost_price' => 300.00,
                'selling_price' => 500.00,
                'stock_quantity' => 20,
                'min_stock_level' => 5,
                'size' => '50g',
                'is_active' => true,
            ],
            [
                'name' => 'Oud Muattar',
                'name_ar' => 'عود معطر',
                'description' => 'Scented Oud blend',
                'barcode' => 'PRF013',
                'sku' => 'ALH-OUM-013',
                'category_id' => 4,
                'brand_id' => 3,
                'cost_price' => 80.00,
                'selling_price' => 150.00,
                'stock_quantity' => 50,
                'min_stock_level' => 10,
                'size' => '40g',
                'is_active' => true,
            ],
            
            // Bakhoor
            [
                'name' => 'Bakhoor Nasaem',
                'name_ar' => 'بخور نسائم',
                'description' => 'Traditional Arabian incense',
                'barcode' => 'PRF014',
                'sku' => 'NAB-BKN-014',
                'category_id' => 5, // Bakhoor
                'brand_id' => 6,
                'cost_price' => 35.00,
                'selling_price' => 65.00,
                'stock_quantity' => 120,
                'min_stock_level' => 30,
                'size' => '40g',
                'is_active' => true,
            ],
            [
                'name' => 'Bakhoor Oud Al Madina',
                'name_ar' => 'بخور عود المدينة',
                'description' => 'Premium Oud incense',
                'barcode' => 'PRF015',
                'sku' => 'ASQ-BOM-015',
                'category_id' => 5,
                'brand_id' => 7,
                'cost_price' => 60.00,
                'selling_price' => 110.00,
                'stock_quantity' => 70,
                'min_stock_level' => 15,
                'size' => '50g',
                'is_active' => true,
            ],
            [
                'name' => 'Bakhoor Maamoul',
                'name_ar' => 'بخور معمول',
                'description' => 'Handmade traditional bakhoor',
                'barcode' => 'PRF016',
                'sku' => 'ALH-BKM-016',
                'category_id' => 5,
                'brand_id' => 3,
                'cost_price' => 40.00,
                'selling_price' => 75.00,
                'stock_quantity' => 90,
                'min_stock_level' => 20,
                'size' => '40g',
                'is_active' => true,
            ],
            
            // Perfume Oils
            [
                'name' => 'Musk Oil',
                'name_ar' => 'زيت المسك',
                'description' => 'Pure concentrated musk oil',
                'barcode' => 'PRF017',
                'sku' => 'AJM-MSO-017',
                'category_id' => 6, // Oils
                'brand_id' => 1,
                'cost_price' => 25.00,
                'selling_price' => 50.00,
                'stock_quantity' => 150,
                'min_stock_level' => 30,
                'size' => '6ml',
                'is_active' => true,
            ],
            [
                'name' => 'Amber Oil',
                'name_ar' => 'زيت العنبر',
                'description' => 'Warm amber concentrated oil',
                'barcode' => 'PRF018',
                'sku' => 'NAB-AMO-018',
                'category_id' => 6,
                'brand_id' => 6,
                'cost_price' => 30.00,
                'selling_price' => 60.00,
                'stock_quantity' => 130,
                'min_stock_level' => 25,
                'size' => '6ml',
                'is_active' => true,
            ],
            [
                'name' => 'Sandalwood Oil',
                'name_ar' => 'زيت الصندل',
                'description' => 'Pure sandalwood essence',
                'barcode' => 'PRF019',
                'sku' => 'ASQ-SDO-019',
                'category_id' => 6,
                'brand_id' => 7,
                'cost_price' => 50.00,
                'selling_price' => 95.00,
                'stock_quantity' => 80,
                'min_stock_level' => 15,
                'size' => '12ml',
                'is_active' => true,
            ],
            [
                'name' => 'Rose Oil',
                'name_ar' => 'زيت الورد',
                'description' => 'Delicate rose perfume oil',
                'barcode' => 'PRF020',
                'sku' => 'LAT-RSO-020',
                'category_id' => 6,
                'brand_id' => 5,
                'cost_price' => 35.00,
                'selling_price' => 70.00,
                'stock_quantity' => 110,
                'min_stock_level' => 20,
                'size' => '6ml',
                'is_active' => true,
            ],
            
            // Premium Luxury Perfumes
            [
                'name' => 'Interlude Man',
                'name_ar' => 'إنترلود رجالي',
                'description' => 'Luxurious spicy oriental fragrance',
                'barcode' => 'PRF021',
                'sku' => 'AMO-INT-021',
                'category_id' => 1,
                'brand_id' => 8, // Amouage
                'cost_price' => 400.00,
                'selling_price' => 650.00,
                'stock_quantity' => 15,
                'min_stock_level' => 3,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Reflection Woman',
                'name_ar' => 'ريفليكشن نسائي',
                'description' => 'Elegant floral fragrance',
                'barcode' => 'PRF022',
                'sku' => 'AMO-REF-022',
                'category_id' => 2,
                'brand_id' => 8,
                'cost_price' => 380.00,
                'selling_price' => 620.00,
                'stock_quantity' => 12,
                'min_stock_level' => 3,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Areej Al Oud',
                'name_ar' => 'عريج العود',
                'description' => 'Rich and complex Oud fragrance',
                'barcode' => 'PRF023',
                'sku' => 'AJM-ARO-023',
                'category_id' => 4,
                'brand_id' => 1,
                'cost_price' => 180.00,
                'selling_price' => 320.00,
                'stock_quantity' => 35,
                'min_stock_level' => 8,
                'size' => '75ml',
                'is_active' => true,
            ],
            [
                'name' => 'Fakhar',
                'name_ar' => 'فخر',
                'description' => 'Pride of Arabian perfumery',
                'barcode' => 'PRF024',
                'sku' => 'LAT-FAK-024',
                'category_id' => 3,
                'brand_id' => 5,
                'cost_price' => 65.00,
                'selling_price' => 120.00,
                'stock_quantity' => 70,
                'min_stock_level' => 15,
                'size' => '100ml',
                'is_active' => true,
            ],
            [
                'name' => 'Attar Al Ghutra',
                'name_ar' => 'عطر الغترة',
                'description' => 'Traditional masculine scent',
                'barcode' => 'PRF025',
                'sku' => 'SWA-ATG-025',
                'category_id' => 1,
                'brand_id' => 4,
                'cost_price' => 75.00,
                'selling_price' => 140.00,
                'stock_quantity' => 55,
                'min_stock_level' => 12,
                'size' => '100ml',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
